### ISSUE TITLE
This library doesn't work

### ISSUE THREAD

**Issue by VladDob** [ParicBat/rpi-pico-i2c-display-lib#1]
I added the library and everything is compiling nicely. But after flashing on the Pico nothing happens and the serial communication stops working too. Actually it seems that nothing works anymore if I even try to use the lcd_init(6, 7); function.

**Comment by paricbat** [comment]
Are you sure that pin 6 is SDA and pin 7 is SCL?
You can try [this](https://github.com/raspberrypi/pico-examples/tree/master/i2c/lcd_1602_i2c) official example for I2C displays, however this one can only do 16x2.

Also it is totally possible that this library does not work anymore, i made it like ages ago :D

**Comment by VladDob** [comment]
I think that might have been it. Thank you
